//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangePrice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        public Currencies()
        {
            this.CurrencyValues = new HashSet<CurrencyValues>();
            this.Operations = new HashSet<Operations>();
        }
    
        public int Id { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencySembol { get; set; }
    
        public virtual ICollection<CurrencyValues> CurrencyValues { get; set; }
        public virtual ICollection<Operations> Operations { get; set; }
    }
}
