//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangePrice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyValues
    {
        public int Id { get; set; }
        public int CurrencyId { get; set; }
        public decimal CurrencyBuying { get; set; }
        public decimal CurrencySelling { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Currencies Currencies { get; set; }
    }
}
