//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangePrice.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExchangePriceEntities1 : DbContext
    {
        public ExchangePriceEntities1()
            : base("name=ExchangePriceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Currencies> Currencies { get; set; }
        public DbSet<CurrencyValues> CurrencyValues { get; set; }
        public DbSet<Operations> Operations { get; set; }
    }
}
